### ISSUE TITLE
No Option to make Darkmode 

### ISSUE THREAD

**Issue by Arthur1236** [JulienMaille/spicetify-dynamic-theme#1]
![Bildschirmfoto von 2021-05-17 22-53advqa-53](https://user-images.githubusercontent.com/37155796/118555613-28dab800-b763-11eb-99aa-f864e5351d62.png)

Hello I'm on Arch Linux and i don't have the Option to turn on Dark Mode. Is this button in the user.css or .js?

**Comment by JulienMaille** [comment]
Hello, the button is added in the javascript code:
https://github.com/JulienMaille/spicetify-dynamic-theme/blob/c34ee130792afd44ce620c44685872ec934df693/default-dynamic.js#L115-L128
Anything showing up in the console?

**Comment by Arthur1236** [comment]
First of all sorry for my English, it is my secondary language:
I think i figured it out. I can't open the Console. I think it is because the Linux Version does not provide any access to the devtools with the new update. Or i didn't find it.

And for some reason other .js Extensions (fullAppDisplay.js) aren't even working either, so I am just going to use Windows, which works perfectly😅
But I keep trying to mess with the files in

**Comment by Arthur1236** [comment]
Marked it as wrong. I managed to open Devtools and saw that that only the Day/Night switch does not load. I dont know of those numbers should be censored or not.
![Bildschirmfoto von 2021-05-18 02-0dfbfb5-00](https://user-images.githubusercontent.com/37155796/118571210-c80ca900-b77d-11eb-86e2-34a8b5e9caec.png)

**Comment by Arthur1236** [comment]
**BEGINNERS FAULT**: I am sorry that I opened an Issue without comparing the Spotify version. Linux currently has Version 1.1.56, instead of 1.1.59 like on Windows which means that only some effects work like Background changing according to the album cover and the font color changing.

I have to wait till the new update hits on Arch.

**Comment by JulienMaille** [comment]
I added a notification popup when Spotify version is too low
