### ISSUE TITLE
[BUG] Scroll extent calculated wrongly

### ISSUE THREAD

**Issue by Pomis** [JulienMaille/spicetify-dynamic-theme#15]
**Describe the bug**
Excess area while scrolling playlists.

**To Reproduce**
Add a lot (50+) playlists and try to scroll them

**Screenshots**
<img width="340" alt="Screenshot 2021-11-01 at 22 41 41" src="https://user-images.githubusercontent.com/7953442/139739169-470e1895-2384-4baa-a75f-b5921f8e8a05.png">

**Desktop:**
 - OS: macOS 11.6
 - Spicetify: v2.7.1
 - Spotify: Spotify for macOS (Apple Silicon) 1.1.71.560.gc21c3367
 - spicetify-dynamic-theme: latest

**What helped me**
I've added these lines to the config file, and it works fine now
```ini
[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}28,
```

**Comment by JulienMaille** [comment]
Is this specific to this theme? Have you tried with stock spicetify?

**Comment by Pomis** [comment]
Oh, yes, you are right. Same happens with default spicetify theme with all extensions disabled

**Comment by Pomis** [comment]
Yes, it's specific to this theme

**Comment by JulienMaille** [comment]
Have you tried removing those lines completely? I think you are coming from `dribbblish-dynamic` theme, but this one here doesn't need patching.

**Comment by Pomis** [comment]
Yes, this is what I've done initially, and when made a screenshot to add to the issue. 
Could this be related to different font rendering on Windows and MacOS?

**Comment by JulienMaille** [comment]
@Pomis is it fixed with `xpui.js_repl_8008=,'${1}58,`?

**Comment by JulienMaille** [comment]
> **What helped me** I've added these lines to the config file, and it works fine now
> 
> ```ini
> [Patch]
> xpui.js_find_8008 = ,(\w+=)32,
> xpui.js_repl_8008 = ,${1}28,
> ```

@Pomis do you confirm `28` is still the right value to fix this issue?
