### ISSUE TITLE
[BUG] Names dont show in light mode

### ISSUE THREAD

**Issue by noxan-dev** [JulienMaille/spicetify-dynamic-theme#18]
**Describe the bug**
The names of your friends and the things they listened to don't change when going into light mode
**To Reproduce**
Have Facebook friends on
turn on light mode
**Screenshots**
![image](https://user-images.githubusercontent.com/59417659/143623689-9af537be-64a5-4d14-8eef-873d10ceba7d.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Version [e.g. 22] 1.1.72

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
(Please paste here console logs or attach a screenshot)
```

**Comment by JulienMaille** [comment]
Probably an issue with spicetify css map? It's ok now
