### ISSUE TITLE
colors freezing if not using skip or previous buttons 

### ISSUE THREAD

**Issue by ITzERI** [JulienMaille/spicetify-dynamic-theme#19]
when i use skip button to change to another song colors will change but when i just press play button that's next to songs colors won't change and freeze to previous songs colors

im on 
win11
 spotify 1.1.73.517
spicetify 2.8.3

hope that helps

**Comment by JulienMaille** [comment]
Can you better explain how to reproduce (or share a short movie)?

**Comment by ITzERI** [comment]
[https://i.imgur.com/dK3njOi.gif](url)

here when i use skip or previous color change but after that color dont change at all only background
