### ISSUE TITLE
How do I remove the release date in the player bar?

### ISSUE THREAD

**Issue by VincentJoshuaET** [JulienMaille/spicetify-dynamic-theme#2]
![image](https://user-images.githubusercontent.com/19756326/119073561-2658b680-ba20-11eb-8fb1-1fc9c94cd507.png)

Looks ugly. There is also no space between it and the artist name.

**Comment by JulienMaille** [comment]
I moved it down to a 3rd line, if you want to remove it, look at this commit: https://github.com/JulienMaille/spicetify-dynamic-theme/commit/68649e11c8489e19df3a63674378d2c3b4b005c8
