### ISSUE TITLE
Circular Artist images

### ISSUE THREAD

**Issue by Gaweringo** [JulienMaille/spicetify-dynamic-theme#22]
**Is your feature request related to a problem? Please describe.**
It just throws me off, when the artist images look just like albums, songs, and so on.

**Describe the solution you'd like**
Making the artist images circular, just as they are in normal Spotify.
Helps to differentiate artist profiles from songs/albums at a glance.

**Describe alternatives you've considered**
I could just update the user.css for myself, but I think this might be something that should be standard for the theme.

**Additional context**
Circular images
![Artist images circular](https://user-images.githubusercontent.com/40121865/147798130-f414510b-e085-4ed7-8e35-238358ee7602.png)

Especially useful in search, where songs/albums and artists are mixed:
![Without circular images](https://user-images.githubusercontent.com/40121865/147798196-6affa26a-b7b9-41a7-9609-82b756fda6d8.png)
![With circular images](https://user-images.githubusercontent.com/40121865/147798205-02e8d8aa-b400-40a7-b027-9affdb17c0c5.png)
![Circular images in recent search](https://user-images.githubusercontent.com/40121865/147798234-81cb0f3f-41d0-4ceb-8ada-31875ff2eb47.png)

**Comment by JulienMaille** [comment]
Agreed
