### ISSUE TITLE
White text on "Your top genres" and "Browse all" cards for better readability

### ISSUE THREAD

**Issue by Gaweringo** [JulienMaille/spicetify-dynamic-theme#23]
**Is your feature request related to a problem? Please describe.**
The text on the cards on the search page is often very hard to read with the colors the theme chooses (see screenshot 1).

**Describe the solution you'd like**
Make the text on the cards on the search page white, or a light gray, so that the text is readable on the different colored backgrounds.

**Describe alternatives you've considered**
I could just update the user.css for myself, but I think this might be something that should be standard for the theme.

`.x-categoryCard-CategoryCard` and `.a2ruVaZt_DdrdHz3GqgU` (?) would need `color: white`, or some other lighter color.
(e.g. `#eaeaea` like most other "white" text)

**Additional context**
Hard to read text (Indie):
![Your top genres cards with dark brown/grey text that is hard to read](https://user-images.githubusercontent.com/40121865/147798615-03fe7a8b-06a9-4863-9ddc-d34b8bbd84dd.png)

Good to read text (white text):
![Your top genres cards with white text that is easy to read](https://user-images.githubusercontent.com/40121865/147798732-9f9ea2a9-ab4b-4a81-b9da-d03044d22e80.png)

**Comment by JulienMaille** [comment]
We can't use `.a2ruVaZt_DdrdHz3GqgU` because these classes change with each spotify update, can you find another selector?

**Comment by Gaweringo** [comment]
```css
#searchPage h3 {
    color: #eaeaea;
}
```
Could be used for "Your top genres" and for "Browse all", as both use `h3`.

And under "Your Library" the liked songs text is also on a colored background and sometimes hard to read.
![Hard to read liked songs text](https://user-images.githubusercontent.com/40121865/147831042-3f4ff993-5a86-41c9-9fd8-8c52f59f1796.png)
So this could also be implemented to make that text white as well:
```css
.main-heroCard-draggable,
.main-heroCard-draggable a,
.main-heroCard-draggable div {
    color: #eaeaea;
}
```

**Comment by JulienMaille** [comment]
Thanks a lot
