### ISSUE TITLE
Missing Dark Mode and Theme falsley applying, for some reason when i try to apply the Theme.

### ISSUE THREAD

**Issue by OuterWild** [JulienMaille/spicetify-dynamic-theme#3]
For some reason when i apply the theme the dynamic part of it works but i dont have a dark/night mode button and the release date isnt showing down where the title is.
![image](https://user-images.githubusercontent.com/84611317/119214518-c0276e80-bac7-11eb-9fea-cfcaa8bc25cb.png)

**Comment by JulienMaille** [comment]
Please do not ignore the bug template and share system details if you want some help

**Comment by OuterWild** [comment]
> Please do not ignore the bug template and share system details and the install procedure you followed if you want some help.
> 
> I would recommend to follow the powershell _no-brainer_ install procedure: https://github.com/JulienMaille/spicetify-dynamic-theme#windows

Hey there, i actually did it throug the powershell procedure!

Also what exact system details do you need?

**Comment by OuterWild** [comment]
> Please do not ignore the bug template and share system details and the install procedure you followed if you want some help.
> 
> I would recommend to follow the powershell _no-brainer_ install procedure: https://github.com/JulienMaille/spicetify-dynamic-theme#windows

Hey there, its fixed, appearently it was a bug on spicetify's End!
