### ISSUE TITLE
Play/Pause Button is Invisible/ Playlist Album Art

### ISSUE THREAD

**Issue by RudySPG** [JulienMaille/spicetify-dynamic-theme#30]
**Describe the bug**
1. Play/Pause Button is Invisible 
2. Playlist show album art

**To Reproduce**
1. Installed on a fresh spotify and spicetify

**Screenshots**
![image](https://user-images.githubusercontent.com/37492880/165250321-ea5fefa8-0bed-4fea-ac47-af86cc523588.png)

**Desktop Setup**
- Operating System: Windows 11
- Spotify: 1.1.83.956.gbe7ea9a7
- Spicetify: 2.9.2
- Theme: 3.6 and 3.7 Tested

**Logs**
Can't get dev tools to work no matter what I try.

**Comment by JulienMaille** [comment]
Latest Spicetify is 2.9.7, make sure to update everything before opening bugs

**Comment by RudySPG** [comment]
okay my bad thought it was updated
