### ISSUE TITLE
I can't apply the transparent background to my spicetify using the DefaultDynamic 

### ISSUE THREAD

**Issue by ChrisMalik** [JulienMaille/spicetify-dynamic-theme#31]
**Describe the bug**
 No transparent colors to my spicetify theme

**To Reproduce**
1.  During the instalation i followed every step correctly and yet i cant apply the background 

**Screenshots**

![image](https://user-images.githubusercontent.com/104471567/165412121-c8a598d9-263d-4fe3-8f49-64189a8e9da3.png)

**Desktop Setup**
- Operating System:  Windows 10
- Spotify:   Spotify 1.1.83.956
- Spicetify: 
- Theme:  DefaultDynamic 

**Logs**

```console
[paste logs here]
```

**Comment by JulienMaille** [comment]
Check your Spicetify version, make sure it's the latest

**Comment by LuvVisk** [comment]
How do you set up the transparent dynamic background?
