### ISSUE TITLE
Add Option to Lock theme into certain color or pick color for theme using color picker.

### ISSUE THREAD

**Issue by foco76** [JulienMaille/spicetify-dynamic-theme#37]
**Is your feature request related to a problem? Please describe.**
### I like to have 3 options called Color Lock , Color Picker and Reset to Defualt-
 **_1.Color Lock-_**
 Use to a lock theme to certain one color picked by album art without changing it per song.
 **_2.Color Picker with Hex code Support-_**
 Manually pick wanted color using color picker and keep that color.
**_3.Reset to Defualt-_**
Remove all Color Locking And Picking Settings.

**Describe the solution you'd like**
**_1.Color Lock-_**    
  When I using this theme it will match color to the current album art Automatically which is awesome,  but think when it does user finds a very beautiful color user wants to set as fixed color in spotify and keep it without changing it's color again when next song starts...So for that Can you add a Color Lock Function?(I Upload some pictures for better understanding..)
_(Please Add this option to both player menu and theme menu!)_
**_2.Color Picker with Hex code Support-_**
Think user needs a custom color (Ex-Orange) So using this user can pick orange color or type relevant hex code and make it fixed color on Spotify as long as he/she wants -
(Please use [https://github.com/yairEO/color-picker](https://github.com/yairEO/color-picker) - Open Source Javascript Minimal Color Picker So it will save some time!😉
**_3.Reset to Defualt-_**
Revert all Color Locking And Picking Settings and make theme settings to default So theme will again starts to match color to the playing song Automatically.

            ♦.Color Lock Deactive-
![Color Lock DA](https://user-images.githubusercontent.com/109255482/190838804-1c489465-60a4-4bb9-a753-5093248a32eb.png)
            
            ♦.Color Lock Active-
![Color Lock Active](https://user-images.githubusercontent.com/109255482/190838839-16d6dd23-eab0-4f32-aa3f-694870aba8e6.png)

            ♦.Menu Normal-
![Menu](https://user-images.githubusercontent.com/109255482/190838874-799ddc99-9cbd-477f-9878-67592eabab70.png)

           ♦.Menu  Expanded-
![Menu Drop](https://user-images.githubusercontent.com/109255482/190838893-8d628462-dc67-4e78-90ae-bb21e0f8ac9d.png)

           ♦.Menu with Color Picker-
![Menu Drop 2](https://user-images.githubusercontent.com/109255482/190838908-eb4fdb1b-75cc-4124-b425-1d70a1a3ea7b.png)

**Comment by JulienMaille** [comment]
Is it a feature you would like to work on and open a PR?

**Comment by foco76** [comment]
I'm Sorry, but I'm not good with javascript (still learning basics of programming! 😅) so I can't do PR  anyhow what i mean is if you can bring this feature to Dynamic Theme it would be awesome! Please try!Thank you!

**Comment by JulienMaille** [comment]
I'm sorry I currently have zero time I can allocate to new features.

**Comment by foco76** [comment]
I understand,Thank you anyway for this theme it's awesome...
BTW is it hard to create color lock function without color picker?after all this theme already support changing color so why not to 
lock into one already there?
