### ISSUE TITLE
Automatic system theme application no longer working

### ISSUE THREAD

**Issue by csforbes** [JulienMaille/spicetify-dynamic-theme#38]
**Describe the bug**
When Spotify desktop is opened with this theme applied, it loads with the Dark theme no matter what the system theme is or what theme was previously set in-app. It does notify "dark theme applied" on first load. When, before, the theme would automatically change in reaction to the system theme, it no longer does.

This started happening after 3 major updates:

1. Spotify updater forced me to redownload the whole app from browser.
2. I ran `spicetify upgrade` to v2.14
3. I re-ran the [MacOS install sh script from the spicetify-dynamic-theme readme](https://github.com/JulienMaille/spicetify-dynamic-theme#linuxmacos-bash).

This is by far my favorite Spicetify theme because of the subtle styling and a _good light theme 😱_, so thank you for the work you've done on this! Sorry if this is an OS, Spicetify, or personal setup issue I'm misinterpreting. 

**To Reproduce**
1. With Spotify quit, Switch MacOS to system light theme.
2. Open Spotify. (Would show Dark theme still)
4. Switch Spotify theme manually to light.
5. Switch MacOS to dark theme. (Spotify would be light still)

**Screenshots**
![Spicetify-dynamic-theme-auto-system-bug](https://user-images.githubusercontent.com/19981645/194361667-a8e8216a-c1c1-49c6-8cd3-b97b554fda4b.gif)

**Desktop Setup**
- Operating System: MacOS 12.6
- Spotify: Spotify for macOS (Intel) 1.1.95.893.g6cf4d40c
- Spicetify: 2.14.0
- Theme: v4.0

**Logs**
```console
cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/8696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-hpto.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/4453.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/7269.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-v2.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/5392.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/8419.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Comment by JulienMaille** [comment]
This feature stopped working months ago due to Spotify. A workaround is available under window relying on patching the .exe file with https://github.com/JulienMaille/spicetify-dynamic-theme/blob/main/patch-dark-mode.ps1
I have no idea if the same can be done under MacOs, can you try?

**Comment by csforbes** [comment]
Thank you. It was weird that it had been working well right until all the updates. I doubt the exact workaround would work on MacOS, but if I get a chance I’ll dig into it.

**Comment by swrobel** [comment]
> I have no idea if the same can be done under MacOs, can you try?

I just tried removing `force-dark-mode` from the macOS binary using a hex editor, and the app won't launch anymore. I notice that you are replacing it with some character (`[byte]65`) - can you explain your strategy a bit and maybe I can get it working on a Mac?

**Comment by JulienMaille** [comment]
FIX thanks to Spotify

**Comment by JulienMaille** [comment]
FIXed thanks to Spotify

**Comment by gdude2002** [comment]
This does not appear to be working - Spotify opens with the dark theme set for me, and I always have to toggle it back to light mode manually.

- Operating System: Windows 11
- Spotify: 1.2.17.834.g26ee1129
- Spicetify: 2.22.1
- Theme: Both 4.6 from the marketplace and `main` branch manual install (https://github.com/JulienMaille/spicetify-dynamic-theme/commit/35408c54c36c193cdc984350d973ad530a1d3514)
