### ISSUE TITLE
Can you help me please?)

### ISSUE THREAD

**Issue by FiftyFour7250** [JulienMaille/spicetify-dynamic-theme#4]
Hey. Thanks for theme, it's really cool. But I have one problem, maybe you can help me? I have ultrawide monitor, and I have slightly stung the left sidebar, so now I have a lot of empty space on the right. This happens on absolutely all pages. Maybe you know what I should write in css, so that I have all the content in the center?

![1](https://user-images.githubusercontent.com/78786088/119870619-3db90780-bf2a-11eb-85b9-db83235aea20.PNG)
![2](https://user-images.githubusercontent.com/78786088/119870629-40b3f800-bf2a-11eb-9d1b-f994744f243c.PNG)
![3](https://user-images.githubusercontent.com/78786088/119870634-41e52500-bf2a-11eb-872f-a4242fb70a76.PNG)

**Comment by JulienMaille** [comment]
I don't have a wide screen so I can't reproduce this
Activate the dev tools and right click "Inspect" this part of the GUI to find which element is responsible for the margin.
![image](https://user-images.githubusercontent.com/182520/119884801-5678eb80-bf31-11eb-8a75-68e76fdd5ce8.png)

**Comment by FiftyFour7250** [comment]
Yea, I found it. Thanks.

**Comment by JulienMaille** [comment]
What was it?

**Comment by FiftyFour7250** [comment]
.contentSpacing
