### ISSUE TITLE
Dislike the spinning album cover.

### ISSUE THREAD

**Issue by 0vm** [JulienMaille/spicetify-dynamic-theme#43]
I dislike the spinning background, I liked it when it was static, is there a way to remove it?

**Comment by JulienMaille** [comment]
I agree it doesn't look that good with latest commit that was meant to reduce the gpu load.
The goal was to have an effect like this: https://codepen.io/darzo27/pen/ZEYyQeL
Do you dislike the effect or my (bad) take on it?

**Comment by 0vm** [comment]
I dislike that the background moves, It distracts me because it is just spinning in the corner of my eye.

**Comment by JulienMaille** [comment]
Have you installed the theme manually or through the Marketplace?

**Comment by 0vm** [comment]
I do not recall

**Comment by JulienMaille** [comment]
If you installed from the marketplace you should now see that:
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/182520/d39f9792-b900-476f-8375-52858eb36c85)

**Comment by 0vm** [comment]
Thank you! The change is very nice, thank you for listening to my feedback, I genuinely appreciate it!
