### ISSUE TITLE
Help Wanted - Dark/ Light Mode Toggle Button

### ISSUE THREAD

**Issue by JSandhu03** [JulienMaille/spicetify-dynamic-theme#45]
Hi,
So I've been using the theme for a bit and am on an older version since I'm on a really old Spotify version. All I wanted to ask was if you could direct me toward where the code for the theme mode toggle is so I could remove the button from the theme for me as it messes with my other extension and custom app toggle locations. 
Thanks for your help and for the theme.

**Comment by JulienMaille** [comment]
https://github.com/JulienMaille/spicetify-dynamic-theme/blob/35408c54c36c193cdc984350d973ad530a1d3514/default-dynamic.js#L146-L158
