### ISSUE TITLE
Match system theme

### ISSUE THREAD

**Issue by gdude2002** [JulienMaille/spicetify-dynamic-theme#47]
**Is your feature request related to a problem? Please describe.**
As someone that primarily uses the light theme and has my system set up in light mode, it's a little jarring on my eyes when I open Spotify, and it's in dark mode by default.

**Describe the solution you'd like**
It'd be nice if this theme was able to make use of a media query (`prefers-color-scheme`) to preselect the light/dark theme by default, matching the system's configuration - if this is possible to do within Spotify's app container.

**Describe alternatives you've considered**
An alternative may be to provide a snippet or configuration option that switches the default theme to light mode instead of dark mode.

Thanks!

**Comment by gdude2002** [comment]
Oops, my mistake, I just noticed #38 - I'll go update that instead.

**Comment by JulienMaille** [comment]
Used to work until last update, Spotify broke it and there's nothing I can do

**Comment by gdude2002** [comment]
Ah, that's unfortunate - in that case, given that the theme comes bundled with an extension, are there any plans to provide a way to change the default, or to split the theme into two (light and dark)?

**Comment by JulienMaille** [comment]
Actually try the patch: https://github.com/JulienMaille/spicetify-dynamic-theme/blob/main/patch-dark-mode.ps1
It worked on my system

**Comment by gdude2002** [comment]
I can confirm that this works - thanks for that!
