### ISSUE TITLE
Weird interface bug (?)

### ISSUE THREAD

**Issue by boobthecat** [JulienMaille/spicetify-dynamic-theme#48]
**Describe the bug**

I don't know if there's anything to describe to be honest. It's just these two colors appearing in the controls panel.
**To Reproduce**
1. Use the theme
2. Be sad

**Screenshots**

![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/127695532/bd2aad00-41e4-4cc8-a35b-67f10f8e5da4)

**Desktop Setup**
- Operating System: <Win 10] -->
- Spotify: <1.2.17.834>
- Spicetify: <2.22.2>
- Theme: <4.6>

![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/127695532/b2b2cee7-99ce-4d63-8c60-510f1c704aba)

**Comment by boobthecat** [comment]
It fixed itself after uninstalling the marketplace version :P

**Comment by JulienMaille** [comment]
Wasn't a bug. But still I removed the left/right borders in latest commit.
