### ISSUE TITLE
I need help!

### ISSUE THREAD

**Issue by Thiagoedlp151** [JulienMaille/spicetify-dynamic-theme#5]
Hi! I want to know if there is any solution for this kind of bug on the top of the window, cause it seems a little bit short than usual. And I want to know if there is any way to remove the Spotify premium sing on the top left.
Sorry for my English, it is not my first language.
![imagen_2021-05-31_223719](https://user-images.githubusercontent.com/84394684/120254684-c1dbf980-c260-11eb-961e-15f186a5bf09.png)

**Comment by JulienMaille** [comment]
Please follow the bug template and give relevant details on your setup, otherwise there is nothing we can do

**Comment by Thiagoedlp151** [comment]
**Describe the bug**
I want to know if there is any solution for this kind of bug on the top of the window, cause it seems a little bit short than usual. And I want to know if there is any way to remove the Spotify premium sing on the top left.

**To Reproduce**
Steps to reproduce the behavior:

**Screenshots**
![imagen_2021-06-01_091226](https://user-images.githubusercontent.com/84394684/120321264-7bff4f80-c2b9-11eb-9d35-950f7a4b9d6d.png)

**Desktop (please complete the following information):**
 - OS:  Windows
 - Version: 10

**Logs**
![imagen_2021-06-01_091312](https://user-images.githubusercontent.com/84394684/120321354-96d1c400-c2b9-11eb-9733-8cd99f6dc9c1.png)

**Comment by Thiagoedlp151** [comment]
Is that the way to describe a bug? sorry if I miss understood the way to do it

**Comment by JulienMaille** [comment]
Thanks, not sure if there's a universal way to describe a bug, but when you need help, you better share some details and context if you want others to understand what's going on.

So back to your issue, it's really weird. I'm wondering if that comes from Spicetify being mis-installed.

Can you go back to the Console screen showing the logs, clear it
![image](https://user-images.githubusercontent.com/182520/120371159-b4347b80-c315-11eb-930d-46a51302ab36.png)
and press F5 to refresh Spotify. Do you still get the red error message?
![image](https://user-images.githubusercontent.com/182520/120371209-c3b3c480-c315-11eb-8e95-6ebfcb3163f8.png)

**Comment by Thiagoedlp151** [comment]
I uninstall spotify and spicetify and it works. Thank you so much!
