### ISSUE TITLE
static background image

### ISSUE THREAD

**Issue by ssamin69** [JulienMaille/spicetify-dynamic-theme#52]
**Is your feature request related to a problem? Please describe.**

the background album art image is moving or rotating

**Describe the solution you'd like**

can i make it static? i want it to not move

**Describe alternatives you've considered**

just make it a static image instead of rotating

**Additional context**

**Comment by ssamin69** [comment]
i deleted some lines in the code its kind of working idk if updating it in the future will break it now

**Comment by JulienMaille** [comment]
If you install through the marketplace you can easily select the NoAnimation variant
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/182520/4aa9956c-9dad-4602-9592-c6c288792e14)

**Comment by ssamin69** [comment]
> If you install through the marketplace you can easily select the NoAnimation variant ![image](https://user-images.githubusercontent.com/182520/281730280-4aa9956c-9dad-4602-9592-c6c288792e14.png)

i did not install from the marketplace

**Comment by JulienMaille** [comment]
> i did not install from the marketplace
Then instead of 
https://github.com/JulienMaille/spicetify-dynamic-theme/blob/960cf51754c329793024524cb9affdb1b6964557/README.md?plain=1#L36-L40
you should call
`spicetify config color_scheme NoAnimation`
