### ISSUE TITLE
Doesn't sync with device theme on Linux

### ISSUE THREAD

**Issue by IdkWhatToCallMe123** [JulienMaille/spicetify-dynamic-theme#56]
**Describe the bug**
Spotify is not syncing light/dark mode on Linux

**To Reproduce**
1. Open spotify
2. Spotify will always default to dark mode even if you have light mode enabled on your system

**Desktop Setup**
- Operating System: Fedora Linux 39
- Spotify: 1.2.26.1187.g36b715a1 (Flatpak)
- Spicetify: 2.29.1
- Theme: 4.8

**Logs**
![圖片](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/74187631/e58e3e10-d608-4edd-b40b-dd1e51b5f33d)

Side note:
Dev tools seems also to default to dark mode even with the theme set to "system preference" and light mode enabled on my system

**Comment by nozerorma** [comment]
Can confirm this also happens in Kubuntu 22.04 LTS + apt Spotify

**Comment by IdkWhatToCallMe123** [comment]
> Can confirm this also happens in Kubuntu 22.04 LTS + apt Spotify

So good to know that it isn't related to Flatpak

**Comment by InfiniteLoopGameDev** [comment]
I have the same issue on Fedora 39 KDE with the Spotify Flatpak

**Comment by JulienMaille** [comment]
Nothing I can do, unfortunately

**Comment by nozerorma** [comment]
Sorry to bump a closed thread, but auto light/dark mode started working today after Spotify/Spicetify update (Plasma 6, Tuxedo OS). Thanks for the theme, its great.

**Comment by JulienMaille** [comment]
@IdkWhatToCallMe123 @nozerorma  have a look at #87
