### ISSUE TITLE
Patcher does not work for lightmode/sync system theme

### ISSUE THREAD

**Issue by vjt4** [JulienMaille/spicetify-dynamic-theme#61]
**Describe the bug**

**To Reproduce**
1. Run Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/JulienMaille/spicetify-dynamic-theme/master/patch-dark-mode.ps1" | Invoke-Expression

**Screenshots**
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/54646079/36ef6f0d-3aae-4d73-bad9-eeb70a51cd5d)

**Desktop Setup**

winver: 
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/54646079/d26b1bcd-5ccb-4c27-b86c-f20ba5f2290c)
any
Spotify for Windows (64 bit)
1.2.31.1205.g4d59ad7c
Spicetify v2.31.3

**Logs**

```console
[Initializing Spicetify Marketplace v0.9.4
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
vendor~xpui.js:1 Loaded Marketplace extension
gue1-spclient.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:1 provider:transport resolve error T ObjectNo properties
(anonymous) @ vendor~xpui.js:1
index.html:1 Uncaught (in promise) Tbody: {error: {…}}headers: A {get: ƒ, has: ƒ}metadata: nulloffline: falseok: falseretries: {count: 0}status: 404timing: nullurl: "https://gue1-spclient.spotify.com/remote-config-resolver/v3/configuration"__sentry_captured__: true[[Prototype]]: Object
xpui.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getProductState')
    at p.handleProductStateUpdate (xpui.js:1:2412025)
    at p._dispatchFromStore (vendor~xpui.js:1:629844)
    at p.emitSync (vendor~xpui.js:1:631313)
    at s.emitSync (xpui.js:1:2251285)
    at s.emitProductStateUpdate (xpui.js:1:2425971)
    at xpui.js:1:2048468
    at vendor~xpui.js:1:5546410
    at onSuccess (xpui.js:1:2252064)]
```

**Comment by JulienMaille** [comment]
Works here
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/182520/5b81fc4e-4e51-4c0c-8ea7-aa1c148a82fd)

**Comment by vjt4** [comment]
PICNIC situation.
I had spicetify installed w/winget & webrequest method at the same time.

After fully clearing everything and following the steps its working again. Just need to remember how i installed it. Thanks
