### ISSUE TITLE
Theme doesn't sync with device theme on MacOS

### ISSUE THREAD

**Issue by LizzardK1ng** [JulienMaille/spicetify-dynamic-theme#67]
**Describe the bug**
Spotify is not syncing light/dark mode on MacOS

**To Reproduce**
1. Installed [**spicetify-dynamic-theme**](https://github.com/JulienMaille/spicetify-dynamic-theme) via **Linux/MacOS (Bash) script** 
2. Open Spotify
3. Light mode can be toggled on manually, does not persist after relaunch
4. **Spotify will always default to dark mode even if you have light/auto mode enabled in OS system settings on launch**
 

**Desktop Setup**
- Operating System: MacOS 10.15.7
- Spotify: Spotify for macOS (Intel)
    - 1.2.33.1042.g26c92729
- Spicetify v2.35.1
    - Theme: DefaultDynamic / base
    - Extensions: default-dynamic.js, Vibrant.min.js
    - Custom apps: marketplace
    - xpui_2024-03-21_1711040982767_26c9272
    - cef_122.1.8+g40272b5+chromium-122.0.6261.69
    - Runtime: Chrome
- Theme: 4.8

**Logs**
```console
index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
extension.js:10 Preloading extensions and themes...
favicon.ico:1 
 Failed to load resource: net::ERR_NAME_NOT_RESOLVED
vendor~xpui.js:1 EmeEncryptionSchemePolyfill: Waiting to detect encryptionScheme support.
vendor~xpui.js:1 McEncryptionSchemePolyfill: Waiting to detect encryptionScheme support.
extension.js:8 Initializing Spicetify Marketplace v1.0.0
extension.js:8 Loaded Marketplace extension
spicetifyWrapper.js:2376 TypeError: Cannot read properties of null (reading '1')
    at checkForUpdate (spicetifyWrapper.js:2265:75)
extension.js:10 
Object
extension.js:10 Parsed 13/13 apps
extension.js:10 No more app results
vendor~xpui.js:1 the token provided isn't working.
extension.js:10 
Object
extension.js:10 Parsed 59/59 themes
extension.js:10 No more theme results
spicetify-routes-marketplace.js:16 No theme set as installed
extension.js:10 
Object
extension.js:10 Parsed 100/108 extensions
vendor~xpui.js:1 created authenticated browser transport
gew1-spclient.spotif…/sessions/current:1 
 Failed to load resource: the server responded with a status of 404 ()
gew1-spclient.spotif…/v3/configuration:1 
 Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:1 provider:transport resolve error 
k
 
Object
index.html:1 Uncaught (in promise) 
k
spicetify-routes-marketplace.js:16 Parsed 59/59 themes
spicetify-routes-marketplace.js:16 No more theme results
preview.webp:1 
 Failed to load resource: the server responded with a status of 404 ()
main/:1 
 Failed to load resource: the server responded with a status of 400 ()
extension.js:10 
Object
extension.js:10 Parsed 200/108 extensions
extension.js:10 No more extension results
[Violation] Forced reflow while executing JavaScript took 114ms
[Violation] Forced reflow while executing JavaScript took 43ms
spicetify-routes-marketplace.js:16 No theme set as installed
spicetify-routes-marketplace.js:16 Parsed 59/59 themes
spicetify-routes-marketplace.js:16 No more theme results
[Violation] Forced reflow while executing JavaScript took 33ms
preview.webp:1 
 GET https://cdn.discordapp.com/attachments/846889355914117140/1147769196772601878/preview.webp 404 (Not Found)
main/:1 
 GET https://raw.githubusercontent.com/Rubutter/notRetroblur/main/ 400 (Bad Request)
Dark.gif:1 
 GET https://xpui.app.spotify.com/Dark.gif net::ERR_NAME_NOT_RESOLVED
windows-shortcut-instruction.png:1 
 GET https://xpui.app.spotify.com/windows-shortcut-instruction.png net::ERR_NAME_NOT_RESOLVED
﻿
```

![Screenshot 2024-03-23 at 10 00 12](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/164612262/11446e4a-9d90-47fa-9a76-5675adde9e80)

**Additional notes:**
Dev-tools also defaults to dark mode even with the theme set to "system preference" and light/auto mode enabled in OS system settings. Can be set to light mode manually - **manual setting does persist when Spotify is relaunched**. See example below:

![Screenshot 2024-03-23 at 10 23 20](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/164612262/977a04bf-6cb8-44d3-b506-15e8a1a27392)

**Comment by JulienMaille** [comment]
Nothing I can do, unfortunately.

**Comment by LizzardK1ng** [comment]
Just took a few minutes to raise awareness :) Thanks for looking in regardless.

_"He who has information, is King."_
