### ISSUE TITLE
The theme working with the new mini player

### ISSUE THREAD

**Issue by riperviwe** [JulienMaille/spicetify-dynamic-theme#68]
Spotify brought a new feature that is the new mini player but the font is black with the theme enabled, so not really visible. is it possible to add the theme to the new mini player?
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/163769124/22b25c0f-d1c3-4546-9e70-8682b7a7f686)

**Comment by JulienMaille** [comment]
It seems it is not possible atm https://github.com/spicetify/spicetify-cli/issues/2836

**Comment by rxri** [comment]
Black text is not even related to spicetify because we don't inject css into mini player files. I don't know what causes this because I cannot even reproduce it
