### ISSUE TITLE
How to Hide Window Controls as you said in README.md?

### ISSUE THREAD

**Issue by GildasEdraE** [JulienMaille/spicetify-dynamic-theme#69]

**Comment by JulienMaille** [comment]
This doesn't work anymore: https://github.com/spicetify/spicetify-themes/issues/902

**Comment by JulienMaille** [comment]
@GildasEdraE you can use this extension from the marketplace: https://github.com/ohitstom/spicetify-extensions?tab=readme-ov-file#nocontrols

**Comment by GildasEdraE** [comment]
Nope that's doesn't work too

**Comment by GildasEdraE** [comment]
> @GildasEdraE you can use this extension from the marketplace: https://github.com/ohitstom/spicetify-extensions?tab=readme-ov-file#nocontrols

Please give me other solutions
