### ISSUE TITLE
[BUG] Missing Vibrant.min.js when installing

### ISSUE THREAD

**Issue by lemonnuggets** [JulienMaille/spicetify-dynamic-theme#7]
**Describe the bug**
Running the install command from README.md leads to an error saying that Vibrant.min.js couldn't be found. Manually adding that file did fix the problem though.

**To Reproduce**
Run `Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/JulienMaille/spicetify-dynamic-theme/master/install.ps1" | Invoke-Expression`

**Screenshots**
![image](https://user-images.githubusercontent.com/63046776/120482127-70517d00-c3ce-11eb-9dd9-4bdf89d20acc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 20H2

**Comment by JulienMaille** [comment]
thanks, the script download the latest release which was older than the commit which added this js file. fixed
