### ISSUE TITLE
Wierd toolbar bug

### ISSUE THREAD

**Issue by WarFiN123** [JulienMaille/spicetify-dynamic-theme#72]
**Describe the bug**
The arrow keys in the toolbar have become extremely big after new Spicetify update.

**To Reproduce**
1. Just install the theme.

**Screenshots**
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/82953540/da48d7c6-7bd8-445d-997c-7bc9b5ba05c0)

**Desktop Setup**
- Operating System: Windows 11 64 bit
- Spotify: 1.2.35.663.gb699649e
- Spicetify: v2.36.8
- Theme: Default Dynamic 

**Logs**
index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
favicon.ico:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
extension.js:8 Initializing Spicetify Marketplace v1.0.1
extension.js:8 Loaded Marketplace extension
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
adblock.js?time=1714150529080:67 [Adblock] Ads disabled Object
adblock.js?time=1714150529080:67 [Adblock] Ads disabled Object
default-dynamic.js?time=1714150529185:285 ReferenceError: Vibrant is not defined
    at pickCoverColor (default-dynamic.js?time=1714150529185:277:28)
    at registerCoverListener (default-dynamic.js?time=1714150529185:296:5)
    at default-dynamic.js?time=1714150529185:313:1
pickCoverColor @ default-dynamic.js?time=1714150529185:285
gae2-spclient.spotify.com/social-connect/v2/sessions/current:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
gae2-spclient.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
 The following functions are deprecated: googletag.pubads().setTagForChildDirectedTreatment(), googletag.pubads().clearTagForChildDirectedTreatment(), googletag.pubads().setRequestNonPersonalizedAds(), and googletag.pubads().setTagForUnderAgeOfConsent(). Please use googletag.pubads().setPrivacySettings() instead.
iB @ securepubads.g.doubl…1/pubads_impl.js:24
vendor~xpui.js:1 provider:transport resolve error k Object
h @ vendor~xpui.js:1
index.html:1 Uncaught (in promise) k

**Comment by JulienMaille** [comment]
Thanks. Have you installed the theme from the PowerShell script or from the marketplace?

**Comment by WarFiN123** [comment]
> Thanks. Have you installed the theme from the PowerShell script or from the marketplace?

Marketplace

**Comment by JulienMaille** [comment]
@WarFiN123 Do you have anything else installed from the marketplace that might conflict?
Can you try to update Spotify to 1.2.36?
I have a very similar setup and can't reproduce your issue
> Spotify pour Windows (64 bits)
1.2.36.955.gd8cc9372
Spicetify v2.36.8
. Theme: Default Dynamic / Base
· Extensions: marketplace, upcomingSong.js, bookmark.js, Vibrant.min.js,
default-dynamic.js
. Custom apps: marketplace
xpui_2024-04-19_1713551583143_d8cc937
cef_122.1.13+gde5b724+chromium-122.0.6261.130
Runtime: Chrome

**Comment by WarFiN123** [comment]
> @WarFiN123 Do you have anything else installed from the marketplace that might conflict? Can you try to update Spotify to 1.2.36? I have a very similar setup and can't reproduce your issue
> 
> > Spotify pour Windows (64 bits)
> > 1.2.36.955.gd8cc9372
> > Spicetify v2.36.8
> > . Theme: Default Dynamic / Base
> > · Extensions: marketplace, upcomingSong.js, bookmark.js, Vibrant.min.js,
> > default-dynamic.js
> > . Custom apps: marketplace
> > xpui_2024-04-19_1713551583143_d8cc937
> > cef_122.1.13+gde5b724+chromium-122.0.6261.130
> > Runtime: Chrome

nevermind its not a theme issue my bad. Spicetify dev told me its a theme issue but its actually a window resize isue
