### ISSUE TITLE
Is there a way to set the background opacity?

### ISSUE THREAD

**Issue by Facu4798** [JulienMaille/spicetify-dynamic-theme#73]
i would like to diminish the blur effect on the album art that dynamically changes in the background, but i dont know which line or file to edit since i dont know webdev. I would really appreciate if you could tell me where can i edit this. Thanks!!

**Comment by JulienMaille** [comment]
You can reduce the blur amount here:
https://github.com/JulienMaille/spicetify-dynamic-theme/blob/ebb53549036802f51f4872e6a2c5dbafd9b37466/user.css#L127
