### ISSUE TITLE
Album Art linked colour no longer changes on song change

### ISSUE THREAD

**Issue by mihirmodi** [JulienMaille/spicetify-dynamic-theme#74]
**Describe the bug**
The custom colour that reflects album art colour would previously change dynamically with song change is broken after Spotify and Spicetify update. The custom colour is now determined by the track in 'Now Playing' when Spotify is launched, but doesn't change when the track changes. 

**To Reproduce**
1. Open Spotify
2. Change song

**Screenshots**

**Desktop Setup**
- Operating System: Windows 11 23H2 Build 22635.2915
- Spotify: 1.2.37.701.ge66eb7bc
- Spicetify: v2.36.11
- Theme: DefaultDynamic

**Comment by mihirmodi** [comment]
I also noticed that the dynamic animated background doesn't work since the update.

**Comment by JulienMaille** [comment]
I just tried today after 5 days afk. Everything still works fine on my setup:
- Operating System: Windows 11 24H2
- Spotify: 1.2.37.701.ge66eb7bc
- Spicetify v2.36.11
- Theme installed from the marketplace

**Comment by mihirmodi** [comment]
Thanks for trying to replicate. Can you suggest any troubleshooting steps? 
- My theme is installed from Marketplace as well
- Spotify patched to enable auto light/dark switching using the script in readme

**Comment by JulienMaille** [comment]
Sure, please paste the errors you see in the Console (as explained in the bug report template)

**Comment by mihirmodi** [comment]
Sorry, I just did a clean reinstall of Spotify & Spicetify and it is working fine now. Perhaps something went wrong during the update process. Issue resolved for me. Thanks!

**Comment by Davoleo** [comment]
mmh, it's a bit inconsistent for me, when the color change fails I get this error in the console:
```
extension.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'replace')
    at ne (extension.js:1:88890)
    at Array.<anonymous> (extension.js:1:89447)
```

Env:
- Spotify: 1.2.37.701.ge66eb7bc
- Spicetify:  v2.36.11
- Theme installed from marketplace

**Comment by JulienMaille** [comment]
Can you try to upgrade Spicetify?

**Comment by Davoleo** [comment]
ok, upgrading from the cli didn't do anything since it was already on the latest version, 
but somehow rerunning the powershell install script fixed the issue, thanks for the suggestion!
