### ISSUE TITLE
Star ratings not displaying correct on now playing bar

### ISSUE THREAD

**Issue by JustTharpy** [JulienMaille/spicetify-dynamic-theme#76]
The colors for the plugin Star Ratings is all one solid thing, wasn't an issue before a while ago.
Works fine in the playlist though
![img-2024-06-04-01-27-55](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/51868481/6bd446a1-fa36-468b-9362-9d35671039b3)

**Comment by JustTharpy** [comment]
SO
```
".main-nowPlayingWidget-nowPlaying svg {
    filter: none !important;
}"``
```
Seems to just fix it, I think a filter was applied over that whole bar, and unintentionally ruined the star ratings.

**Comment by JulienMaille** [comment]
Hi, I'm currently too busy to look into this. I will try your fix when I have some time. Beware this filter was meant to color the "like" animation of the heart icon.

**Comment by JustTharpy** [comment]
Thanks and no rush!
