### ISSUE TITLE
Installing Default Dynamic through Marketplace with Beautiful Lyrics crashes Spotify

### ISSUE THREAD

**Issue by MS-64** [JulienMaille/spicetify-dynamic-theme#77]
**Describe the bug**
When Default Dynamic is installed through the Marketplace with Beautiful Lyrics installed too, Spotify will loop reload a few times before crashing/closing. Happens most of the time when opening Spotify but not every time. This has been an issue for a while now. Installing Default Dynamic through the PowerShell script does not have this issue which makes me believe this is a bug with Default Dynamic when installed through the Marketplace but please tell me if I'm wrong. for some reason quickly clicking the Light/Dark mode button prevents this from happening.

**To Reproduce**
1. Install Default Dynamic through Marketplace
2. Install Beautiful Lyrics through Marketplace
3. Close and reopen or Refresh Spotify

**Screenshots**

https://github.com/JulienMaille/spicetify-dynamic-theme/assets/141533012/ce5c12a3-e4ad-411b-86e1-2f472a2c6af9

**Desktop Setup**
- Operating System: Windows 11
- Spotify: 1.2.39.578.g0ea3f38b
- Spicetify: 2.36.12
- Theme: 4.9

**Logs**

![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/141533012/dcca926b-f6e7-4aa3-838b-4e3175a914fe)

**Comment by JulienMaille** [comment]
I have no idea how to solve that, have you also contacted the team behind Beautiful Lyrics and the Marketplace?

**Comment by sanoojes** [comment]
am also facing the same issue its crashing when devtools is enabled
