### ISSUE TITLE
Album year doesn't show correctly (Invalid Date) 

### ISSUE THREAD

**Issue by Kojimboy** [JulienMaille/spicetify-dynamic-theme#78]
**Describe the bug**
Album year is not shown correctly (Invalid Date)

**To Reproduce**
1. Install Dynamic theme
2. Play any song

**Screenshots**

![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/62707231/bc855dc3-9d0e-4cde-b6b7-dd04f56f9310)

**Desktop Setup**
- Operating System:  Alt Linux kde 5, Fedora 40 Kde 6
- Spotify:  Spotify   installed from flatpak 1.2.37.701.ge66eb7bc  
- Spicetify:  2.36.12
- Theme:  4.9

**Logs**

![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/62707231/c28819ad-9616-4b60-9f2e-b02f4601ce7d)

**Comment by JulienMaille** [comment]
I'm unable to reproduce this on Windows, theme installed from MarketPlace.
![image](https://github.com/JulienMaille/spicetify-dynamic-theme/assets/182520/26252a88-280b-4bc2-976d-2d340f27d549)

**Comment by Kojimboy** [comment]
Yeah it reproduces cause spotify is blocked in my country, although i can use it without vpn (after i login with vpn). If i turn on vpn and restart spotify it starts to show date correctly. I wonder if there is another way to code getting album year without needing to have vpn to see it, cause anything other than that works correctly without vpn. Also it would be super cool to have ability to customize this wonderful theme directly from spotify (set different background animation settings or turn it off completely). I know that i can do that by modifying css and js files, but that's not so convenient and user friendly

**Comment by eightelb** [comment]
i dont know anything about coding but i tried experimenting and just removed the album date for myself

before:

`



    let nearArtistSpanText = "";
    async function songchange() {
        if (!document.querySelector(".main-trackInfo-container")) return setTimeout(songchange, 300);
        try {
            // warning popup
            if (Spicetify.Platform.PlatformData.client_version_triple < "1.1.68") Spicetify.showNotification(`Your version of Spotify ${Spicetify.Platform.PlatformData.client_version_triple}) is un-supported`);
        } catch (err) {
            console.error(err);
        }
    
        let album_uri = Spicetify.Player.data.item.metadata.album_uri;
        let bgImage = Spicetify.Player.data.item.metadata.image_url;
        if (!bgImage) {
            bgImage = "https://cdn.jsdelivr.net/gh/JulienMaille/spicetify-dynamic-theme@main/images/tracklist-row-song-fallback.svg";
            textColor = "#1db954";
            updateColors(textColor);
        }
    
        if (album_uri && !album_uri.includes("spotify:show")) {
            const albumInfo = await getAlbumInfo(album_uri.replace("spotify:album:", ""));
            let album_date = new Date(albumInfo.release_date);
            let recent_date = new Date();
            recent_date.setMonth(recent_date.getMonth() - 6);
            album_date = album_date.toLocaleString("default", album_date > recent_date ? { year: "numeric", month: "short" } : { year: "numeric" });
            nearArtistSpanText = `
                <span>
                    <span draggable="true">
                        <a draggable="false" dir="auto" href="${album_uri}">${Spicetify.Player.data.item.metadata.album_title}</a>
                    </span>
                </span>
                <span> • ${album_date}</span>
            `;
        } else if (Spicetify.Player.data.item.type === "episode") {
            // podcast
            const episodeInfo = await getEpisodeInfo(Spicetify.Player.data.item.uri.replace("spotify:episode:", ""));
            let podcast_date = new Date(episodeInfo.release_date);
            podcast_date = podcast_date.toLocaleString("default", { year: "numeric", month: "short" });
            bgImage = bgImage.replace("spotify:image:", "https://i.scdn.co/image/");
            nearArtistSpanText = `
                <span>
                    <span draggable="true">
                        <a draggable="false" dir="auto" href="${album_uri}">${Spicetify.Player.data.item.metadata["show.publisher"]}</a>
                    </span>
                </span>
                <span> • ${podcast_date}</span>
            `;
        } else if (Spicetify.Player.data.item.isLocal) {
            // local file
            nearArtistSpanText = Spicetify.Player.data.item.metadata.album_title;
        } else if (Spicetify.Player.data.item.provider == "ad") {
            // ad
            nearArtistSpanText.innerHTML = "Advertisement";
            return;
        } else {
            // When clicking a song from the homepage, songChange is fired with half empty metadata
            // todo: retry only once?
            setTimeout(songchange, 200);
        }

        if (!document.querySelector("#main-trackInfo-year")) {
            waitForElement([".main-trackInfo-container:not(#upcomingSongDiv)"], (queries) => {
                nearArtistSpan = document.createElement("div");
                nearArtistSpan.id = "main-trackInfo-year";
                nearArtistSpan.classList.add("main-trackInfo-release", "standalone-ellipsis-one-line", "main-type-finale");
                nearArtistSpan.innerHTML = nearArtistSpanText;
                queries[0].append(nearArtistSpan);
            });
        } else {
            nearArtistSpan.innerHTML = nearArtistSpanText;
        }
        document.documentElement.style.setProperty("--image_url", `url("${bgImage}")`);
        pickCoverColor();
    }
`


after:
`



    let nearArtistSpanText = "";
    async function songchange() {
        if (!document.querySelector(".main-trackInfo-container")) return setTimeout(songchange, 300);
        try {
            // warning popup
            if (Spicetify.Platform.PlatformData.client_version_triple < "1.1.68") Spicetify.showNotification(`Your version of Spotify ${Spicetify.Platform.PlatformData.client_version_triple}) is un-supported`);
        } catch (err) {
            console.error(err);
        }
    
        let album_uri = Spicetify.Player.data.item.metadata.album_uri;
        let bgImage = Spicetify.Player.data.item.metadata.image_url;
        if (!bgImage) {
            bgImage = "https://cdn.jsdelivr.net/gh/JulienMaille/spicetify-dynamic-theme@main/images/tracklist-row-song-fallback.svg";
            textColor = "#1db954";
            updateColors(textColor);
        }
    
        if (album_uri && !album_uri.includes("spotify:show")) {
            const albumInfo = await getAlbumInfo(album_uri.replace("spotify:album:", ""));
            let album_date = new Date(albumInfo.release_date);
            nearArtistSpanText = `
                <span>
                    <span draggable="true">
                        <a draggable="false" dir="auto" href="${album_uri}">${Spicetify.Player.data.item.metadata.album_title}</a>
                    </span>
                </span>
                <span>
            `;
        } else if (Spicetify.Player.data.item.type === "episode") {
            // podcast
            const episodeInfo = await getEpisodeInfo(Spicetify.Player.data.item.uri.replace("spotify:episode:", ""));
            bgImage = bgImage.replace("spotify:image:", "https://i.scdn.co/image/");
            nearArtistSpanText = `
                <span>
                    <span draggable="true">
                        <a draggable="false" dir="auto" href="${album_uri}">${Spicetify.Player.data.item.metadata["show.publisher"]}</a>
                    </span>
                </span>
                <span>
            `;
        } else if (Spicetify.Player.data.item.isLocal) {
            // local file
            nearArtistSpanText = Spicetify.Player.data.item.metadata.album_title;
       } else if (Spicetify.Player.data.item.provider == "ad") {
            // ad
            nearArtistSpanText.innerHTML = "Advertisement";
            return;
        } else {
            // When clicking a song from the homepage, songChange is fired with half empty metadata
            // todo: retry only once?
            setTimeout(songchange, 200);
        }
    
       if (!document.querySelector("#main-trackInfo-year")) {
            waitForElement([".main-trackInfo-container:not(#upcomingSongDiv)"], (queries) => {
                nearArtistSpan = document.createElement("div");
                nearArtistSpan.id = "main-trackInfo-year";
                nearArtistSpan.classList.add("main-trackInfo-release", "standalone-ellipsis-one-line", "main-type-finale");
                nearArtistSpan.innerHTML = nearArtistSpanText;
                queries[0].append(nearArtistSpan);
            });
        } else {
            nearArtistSpan.innerHTML = nearArtistSpanText;
        }
        document.documentElement.style.setProperty("--image_url", `url("${bgImage}")`);
        pickCoverColor();
    }
`
