### ISSUE TITLE
Add a customizabile fixed accent color instead of changing based on the album cover

### ISSUE THREAD

**Issue by nicola02nb** [JulienMaille/spicetify-dynamic-theme#79]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like a customizable fixed color, editable from maketplace theme settings

**Comment by JulienMaille** [comment]
The whole idea with this theme is to follow the album art. Unless someones comes with a PR I don't have time to work on this kind of feature, sorry.
