### ISSUE TITLE
[BUG] Error 404 from URL in install script

### ISSUE THREAD

**Issue by lapis-lazulon** [JulienMaille/spicetify-dynamic-theme#8]
Hey! https://api.github.com/repos/JulienMaille/default-dynamic-theme/releases/latest is returning an error 404 for me (and others I've asked to try and run install.sh) when following the install instructions for Mac/Linux (on Linux btw).
![image](https://user-images.githubusercontent.com/56394759/122974018-c2f8d600-d389-11eb-877e-4019554d3861.png)

**Comment by JulienMaille** [comment]
Thanks for pointing this out.
