### ISSUE TITLE
Option to disable texts' color changing

### ISSUE THREAD

**Issue by Alpointernet** [JulienMaille/spicetify-dynamic-theme#80]
**Is your feature request related to a problem? Please describe.**
It is. So basically, this problem is because most of the text's color changes depending on the album cover. The text's color most likely turns into a dark color (especially if the cover art is mostly red), and this makes the text unreadable.

**Describe the solution you'd like**
Add an option to disable text's color change. (So keep the text color white like default)

**Describe alternatives you've considered**
The text's color can change, but slightly. Like; the text color will still be white, but it has a little "red" (depending on the song cover). So it will be still close to white, but not fully. (This sounds like a better idea tbh)

**Additional context**
As example, I cant read these text from my normal viewing distance, I need to get closer just to read the text.
![Screenshot 2024-07-17 115354](https://github.com/user-attachments/assets/45660983-9ea0-458a-88d2-8f943f71c432)

Example 2:
![image](https://github.com/user-attachments/assets/7a7bd739-846e-4b7c-b415-1b9dac10c873)

Example 3:
![Screenshot 2024-07-17 195447](https://github.com/user-attachments/assets/72115618-7430-459b-9d0e-8ab471dc43cf)

**Comment by JulienMaille** [comment]
Can you try changing this value to something greater (0 or more) and then report if the text readability is improved?
Thank you
https://github.com/JulienMaille/spicetify-dynamic-theme/blob/33420415072628a7f1f9e8860b16027ee3c334c9/user.css#L5

**Comment by Alpointernet** [comment]
> Can you try changing this value to something greater (0 or more) and then report if the text readability is improved? Thank you
> 
> https://github.com/JulienMaille/spicetify-dynamic-theme/blob/33420415072628a7f1f9e8860b16027ee3c334c9/user.css#L5

I did try what you said, but it just made the text color spotify green. Also I dont seem to be able to reset it back how it was (to dynamic text color) or change the color of the text to anything else. I tried reinstalling spicetify, reinstalling the theme, but nothing did help. I tried this with my friend at the same time and he has the same issue now. Text color turned into green and stuck on that color.
![Screenshot 2024-07-17 235451](https://github.com/user-attachments/assets/7f273d50-b33a-4bd3-b610-96dfa5065644)

**Comment by JulienMaille** [comment]
I  looked into this and I was wrong: that parameter is not used anymore. You probably messed something up because changing its value should have no effect at all.

**Comment by Alpointernet** [comment]
> I  looked into this and I was wrong: that parameter is not used anymore. You probably messed something up because changing its value should have no effect at all.

Okay then, I will just do a clear reinstallation of everything to see if that does fix anything. Thanks for your time. Lemme hear if you have a solution to my main problem, you can take your time :)

**Comment by sesocell** [comment]
> I looked into this and I was wrong: that parameter is not used anymore. You probably messed something up because changing its value should have no effect at all.

@JulienMaille 
I think he forgot copying the Vibrant.min.js to extensions folder I updated the installation guide #81

**Comment by Alpointernet** [comment]
Edit: The new update fixed the "Example 2", but still not the other one.

**Comment by JulienMaille** [comment]
Can you share same examples than 1 and 3 but with latest release?

**Comment by JulienMaille** [comment]
You know the theme is supposed to switch from white to dark? Provided you run the PowerShell script? I tune the dark theme mostly for an evening/night use when text contrast is usually less of a problem

**Comment by Alpointernet** [comment]
> You know the theme is supposed to switch from white to dark? Provided you run the PowerShell script? I tune the dark theme mostly for an evening/night use when text contrast is usually less of a problem

Yeah, that makes sense. So I guess we can close this issue. Thanks for your help.
