### ISSUE TITLE
sorry this is not an issue( is there a theme that just syncs to the dark or light mode for the device  )

### ISSUE THREAD

**Issue by AboodeDaBOSS** [JulienMaille/spicetify-dynamic-theme#82]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by JulienMaille** [comment]
This theme syncs dark an light mode and, using the right patch, should work on Windows, Mac and Linux
