### ISSUE TITLE
Dark mode area while using Light mode on Sidebar

### ISSUE THREAD

**Issue by SupLiCatinG** [JulienMaille/spicetify-dynamic-theme#84]
**Describe the bug**
As described on title

**To Reproduce**
I have enabled show credits on sidebar with experimental features but not this is not the only issue.
**Screenshots**

**Desktop Setup**
- Operating System: Windows 10 21H2 LTSC IOT Build 19044.4651
- Spotify:Spotify für Windows (32 Bit) 1.2.43.420.gc7b23f70
- Spicetify: Spicetify v2.36.15
- Theme: 5.0

![image](https://github.com/user-attachments/assets/d3b9ca8f-f160-4975-95a7-93214b27720c)
![image](https://github.com/user-attachments/assets/8443433b-1071-45e3-9825-7a1f7cf3f2c7)

```

**Comment by JulienMaille** [comment]
Try to upgrade spicetify, it fixed by itself.
