### ISSUE TITLE
Theming for the new nav bar

### ISSUE THREAD

**Issue by masuteri** [JulienMaille/spicetify-dynamic-theme#85]
The new naw bar (accessible with [this](https://github.com/user-attachments/assets/35b9499f-f9b2-40aa-b3e9-4fd232c78dcf) setting doesn't match the rest of the theme 
![kuva](https://github.com/user-attachments/assets/1fc40883-1358-41f4-a728-5ffbb9b109ad)

**Comment by JulienMaille** [comment]
I wasn't able to enable the new bar despite checking the corresponding experimental option.

**Comment by masuteri** [comment]
are you sure? It may require a restart

**Comment by JulienMaille** [comment]
What's wrong with it, it's not clear from your pic
