### ISSUE TITLE
FYI: Hex editing the spotify binary on linux works to disable forced dark mode.

### ISSUE THREAD

**Issue by Covkie** [JulienMaille/spicetify-dynamic-theme#87]
replacing the string `force-dark-mode` with an array of null(00) bytes to fill the space works to disable forced dark mode on Linux.

I am assuming the same applies to MacOS. 

IMO this should really be an option within spicetify cli. I might pr if I feel bothered :p

**Comment by JulienMaille** [comment]
Great finding! Do you think you could write a bash script that does that automatically? Ie find the address and overwrite a few bytes?

**Comment by JulienMaille** [comment]
Great finding! Do you think you could write a bash script that does that automatically? Ie find the address and overwrite a few bytes?

**Comment by JulienMaille** [comment]
Sure, let me know how you would like to be mentioned as a coauthor?

**Comment by JulienMaille** [comment]
Here you go, looks good to you?

**Comment by JulienMaille** [comment]
I agree the backup is kinda useless.
Do you want to submit your own PR?
