### ISSUE TITLE
Is it possible to adjust the visual parameters (so to make the colors less dull / inaccurate)?

### ISSUE THREAD

**Issue by e391hed12** [JulienMaille/spicetify-dynamic-theme#91]
Like blur, saturation, color fetching mode, etc.

I loved the idea of a dynamic theme so much!! it's takes the spotify experience to the next level -- but in practice the colors often seem to be so hit or miss! 
Here's an example:
![image](https://github.com/user-attachments/assets/49328aed-1a15-475a-821c-cd5a78b2646b)

And what I would like to achieve for reference: (Beautiful Lyrics' dynamic background)
![image](https://github.com/user-attachments/assets/fa682f5f-48bc-487f-a0e1-368e43547c70)

**Comment by JulienMaille** [comment]
I have no plans to work on color extraction, I have found https://jariz.github.io/vibrant.js/ to work quite well.
You are welcome to work on the code and submit a PR though
