### ISSUE TITLE
Theme application + light mode on startup

### ISSUE THREAD

**Issue by e391hed12** [JulienMaille/spicetify-dynamic-theme#92]
Every time I open spotify, I need to play a new song, even if one is already playing, in order to get the theme to kick in. Is that fixable?

And I tried the .ps1 patch for light mode but I only got a "Failed to patch the file" message (Windows 11). Any idea why that might be? I'm not very tech-savy sorry so I don't know what info or specs to relay, but if someone tells me I'll gladly do it

**Comment by JulienMaille** [comment]
> Every time I open spotify, I need to play a new song, even if one is already playing, in order to get the theme to kick in. Is that fixable?

This should be fixed with 5.3
