### ISSUE TITLE
light mode buttom appears broken

### ISSUE THREAD

**Issue by masuteri** [JulienMaille/spicetify-dynamic-theme#93]
![{FE61507A-8073-47F4-939F-DF72625FF0AA}](https://github.com/user-attachments/assets/35f5399c-6d2a-442e-90f9-e3cd87dbd281)
This happens on newest version (1.2.47)
Please also make a new release after making a fix, so we can use the install script.

**Comment by SCENEMOLUV** [comment]
+1
