### ISSUE TITLE
Album Art metadata issue

### ISSUE THREAD

**Issue by PowerChordGamer** [JulienMaille/spicetify-dynamic-theme#96]
When playing a playlist that consists of both local files from the computer and native spotify songs, the album art will fail to load when switching between the two

![image](https://github.com/user-attachments/assets/95327272-6658-4a19-b27a-56e36c1f9728)
![image](https://github.com/user-attachments/assets/48a9cca0-adca-43af-9d09-59be38166d9a)

**Comment by JulienMaille** [comment]
Should be fixed with latest commit
