### ISSUE TITLE
theme is not working

### ISSUE THREAD

**Issue by SantiPT007** [JulienMaille/spicetify-dynamic-theme#98]
redoing the bug report but this time properly

![image_2024-10-19_143549491](https://github.com/user-attachments/assets/dc17dec4-5e2d-4cf9-85cb-df8e5b569554)
![image_2024-10-19_143601086](https://github.com/user-attachments/assets/9e24148a-b430-4300-a3b3-b41cf5713900)

- Operating System: Windows 10 22H2
- Spotify: Spotify for Windows (64 bit) 1.2.48.405.gf2c48e6f
- Spicetify: v2.38.4
- Theme: v5.4

- Logs:

```console
 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
CircularSp-Book.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSp-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSpTitle-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSpTitle-Black.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
spicetifyWrapper.js:453 [spicetifyWrapper] Waiting for required webpack modules to load
4151.css:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
favicon.ico:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
spicetifyWrapper.js:474 [spicetifyWrapper] All required webpack modules loaded
extension.js:8 Initializing Spicetify Marketplace v1.0.2
extension.js:8 Loaded Marketplace extension
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
gew1-spclient.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:1 provider:transport resolve error e Object
g @ vendor~xpui.js:1
adblock.js?time=1729345112687:67 [Adblock] Ads disabled Object
index.html:1 Uncaught (in promise) e
adblock.js?time=1729345112687:67 [Adblock] Ads disabled Object
default-dynamic.js:284 Uncaught SyntaxError: Unexpected token 'else'
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSpTitle-Bold.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSpTitle-Black.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSp-Bold.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSp-Book.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by SantiPT007** [comment]
I would like to add that I found out the theme does not change the "playing now view" so the theme is not working at all

**Comment by JulienMaille** [comment]
Thanks for redoing the bug report. I'm wondering if there's incompatibility with one of the (many) extension & snippets you have installed. Can you troubleshoot it by disabling some of them and see if it helps?

**Comment by BurnedPinguin** [comment]
I am exhibiting the same issue since about 6 hours now. The playing now view's theme comes from the beautiful lyrics plugin. Dynamic Theme has been broken in its entirety. Spotify pour Windows (64 bits) 1.2.37.701.ge66eb7bc + Spicetify v2.38.4

**Comment by SantiPT007** [comment]
> Thanks for redoing the bug report. I'm wondering if there's incompatibility with one of the (many) extension & snippets you have installed. Can you troubleshoot it by disabling some of them and see if it helps?

sure i could try

**Comment by SantiPT007** [comment]
> I am exhibiting the same issue since about 6 hours now. The playing now view's theme comes from the beautiful lyrics plugin. Dynamic Theme has been broken in its entirety. Spotify pour Windows (64 bits) 1.2.37.701.ge66eb7bc + Spicetify v2.38.4

yea I realized the playing now view is from the lyrics plugin

**Comment by SantiPT007** [comment]
> Thanks for redoing the bug report. I'm wondering if there's incompatibility with one of the (many) extension & snippets you have installed. Can you troubleshoot it by disabling some of them and see if it helps?

nope its fully broken, I removed every extension and snippet

logs with only the dynamic theme installed
,,,
index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
CircularSpTitle-Black.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSpTitle-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSp-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSp-Book.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
spicetifyWrapper.js:453 [spicetifyWrapper] Waiting for required webpack modules to load
4151.css:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
favicon.ico:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
spicetifyWrapper.js:474 [spicetifyWrapper] All required webpack modules loaded
extension.js:8 Initializing Spicetify Marketplace v1.0.2
extension.js:8 Loaded Marketplace extension
default-dynamic.js:284 Uncaught SyntaxError: Unexpected token 'else'
gew1-spclient.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:1 provider:transport resolve error e Object
g @ vendor~xpui.js:1
index.html:1 Uncaught (in promise) e
12The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSpTitle-Bold.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSpTitle-Black.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSp-Bold.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSp-Book.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSpTitle-Bold.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSpTitle-Black.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSp-Bold.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSp-Book.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSpTitle-Bold.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSpTitle-Black.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSp-Bold.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
index.html:1 The resource https://xpui.app.spotify.com/fonts/CircularSp-Book.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
,,,

**Comment by JulienMaille** [comment]
According to your logs you seems to have a syntax error:
> default-dynamic.js:284 Uncaught SyntaxError: Unexpected token 'else'
this might come from a previous commit that is still in the cache loaded by the marketplace. I would recommend to wait 24h and retry

**Comment by SantiPT007** [comment]
> According to your logs you seems to have a syntax error:
> 
> > default-dynamic.js:284 Uncaught SyntaxError: Unexpected token 'else'
> 
> this might come from a previous commit that is still in the cache loaded by the marketplace. I would recommend to wait 24h and retry

alright thanks, I will let you know what happens in 24h then

**Comment by SantiPT007** [comment]
hey you were right! It's working normally now
